#
# This source file is part of the StanfordBDHG Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

project: TemplateApplication.xcodeproj
schemes:
- TemplateApplication
targets:
- TemplateApplication
- TemplateApplicationTests
- TemplateApplicationUITests
- TemplateWatchApplication
