#
# This source file is part of the StanfordBDHG Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  reuse_action:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
  periphery:
    name: Periphery
    uses: StanfordBDHG/.github/.github/workflows/periphery.yml@v2
    permissions:
      contents: read
  codeql:
    name: CodeQL
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      codeql: true
      fastlanelane: codeql
    permissions:
      security-events: write
      actions: read
  buildandtest:
    name: Build and Test
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    strategy:
      fail-fast: false
      matrix:
        platform: [iphone, ipad, apple_watch, apple_tv, vision_pro]
    with:
      # We use the self-hosted runners as the main GitHub Action runners do not have the necessary performance.
      # Remove the `runsonlabels: '["macOS", "self-hosted"]'` lines if you do not administer your own GitHub Runners.
      runsonlabels: '["macOS", "self-hosted"]'
      fastlanelane: test_${{ matrix.platform }}
      artifactname: ${{ matrix.platform }}.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: iphone.xcresult ipad.xcresult apple_watch.xcresult apple_tv.xcresult vision_pro.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
